services:
  oracle:
    image: oracle/database:19.3.0-ee
    container_name: oracle-db
    restart: always
    environment:
      ORACLE_SID: ${ORACLE_SID}
      ORACLE_PDB: ${ORACLE_PDB}
      ORACLE_PWD: ${ORACLE_PWD}
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/${ORACLE_PWD}@//localhost:1521/${ORACLE_SID} as sysdba", "exit"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle_data:
